default_stages:
  - commit
fail_fast: true
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        exclude: "interactive/interpreter"
      - id: check-json
      - id: check-merge-conflict
  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.1
    hooks:
      - id: go-fmt
      - id: go-vet
      - id: go-imports
      - id: go-unit-tests
      - id: go-build
      - id: go-mod-tidy
  - repo: local
    hooks:
      - id: go-build-interactive
        name: go-build-interactive
        # git add after mv to prevent pre-commit error
        entry: >
          sh -c '\
            make build_static \
            && mv interpreter interactive \
            && git add interactive/interpreter \
          '
        language: golang
        pass_filenames: false
