version: "3"
services:
  interpreter:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 8501:8501
    volumes:
      - ..:/workspace:cached
      - ~/.ssh:/home/nonroot/.ssh:ro
    command: /bin/sh -c "while sleep 1000; do :; done"
